export const products = [
  {
    mini1: '../img/polo-front.jpg',
    discrfoto1: 'Polo-front',
    bigMini1: '../img/polo-front-big.jpg',
    mini2: '../img/polo-back.jpg',
    discrfoto2: 'Polo-back',
    bigMini2: '../img/polo-back-big.jpg',
    mini3: '../img/polo-close-up.jpg',
    discrfoto3: 'Polo-close-up',
    bigMini3: '../img/polo-close-up-big.jpg',
    preview: '../img/polo-main.jpg',
    original: '../img/polo-main-big.jpg',
    link: 'https://www.ralphlauren.com',
    title: 'Custom Fit Polo Bear Oxford Shirt',
    description:
      'Blue polo with a classic cut. Made of smooth and soft cotton.',
    price: 132,
    discount: 25,
  },
  {
    mini1: '../img/2-front.jpg',
    discrfoto1: 'Polo-front',
    bigMini1: '../img/2-front-big.jpg',
    mini2: '../img/2-back.jpg',
    discrfoto2: 'Polo-back',
    bigMini2: '../img/2-back-big.jpg',
    mini3: '../img/2-close-up.jpg',
    discrfoto3: 'Polo-close-up',
    bigMini3: '../img/2-close-up-big.jpg',
    preview: '../img/2-main.jpg',
    original: '../img/2-main-big.jpg',
    link: 'https://www.ralphlauren.com',
    title: 'T-Shirt Polo Ralph Lauren ',
    description: 'женская 211891673',
    price: 100,
    discount: 5,
  },
];
